e_commerce/accounts/urls.py
from django.urls import path, include
from .views import SignUpView



"""
accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']

"""

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
     path('signup/', SignUpView.as_view(), name='signup'),
]

e_commerce/cartApi/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CartViewSet, CartItemViewSet

router = DefaultRouter()
router.register(r'my-cart', CartViewSet)
router.register(r'my-cart-items', CartItemViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("products.urls")),
    path("accounts/",include("accounts.urls")),
    path("api/",include("cartApi.urls"))
]

e_commerce/accounts/models.py
from django.db import models



    

# Create your models here.

e_commerce/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

e_commerce/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('login')  # Redirect to the login page after successful registration

# Create your views here.

e_commerce/accounts/templates/signup.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1 class="text-center mb-4">Sign Up</h1>
  <hr />

  <form method="POST" class="bg-light p-4 rounded shadow-sm">
    {% csrf_token %}

    <div class="mb-3">
      <label for="id_username" class="form-label">Username</label>
      <input
        type="text"
        name="username"
        class="form-control"
        id="id_username"
        value="{{ form.username.value|default_if_none:'' }}"
        required
      />
      {% if form.username.errors %}
      <div class="text-danger">
        {% for error in form.username.errors %}
        <p>{{ error }}</p>
        {% endfor %}
      </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="id_email" class="form-label">Email</label>
      <input
        type="email"
        name="email"
        class="form-control"
        id="id_email"
        value="{{ form.email.value|default_if_none:'' }}"
        required
      />
      {% if form.email.errors %}
      <div class="text-danger">
        {% for error in form.email.errors %}
        <p>{{ error }}</p>
        {% endfor %}
      </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="id_first_name" class="form-label">First Name</label>
      <input
        type="text"
        name="first_name"
        class="form-control"
        id="id_first_name"
        value="{{ form.first_name.value|default_if_none:'' }}"
        required
      />
      {% if form.first_name.errors %}
      <div class="text-danger">
        {% for error in form.first_name.errors %}
        <p>{{ error }}</p>
        {% endfor %}
      </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="id_last_name" class="form-label">Last Name</label>
      <input
        type="text"
        name="last_name"
        class="form-control"
        id="id_last_name"
        value="{{ form.last_name.value|default_if_none:'' }}"
        required
      />
      {% if form.last_name.errors %}
      <div class="text-danger">
        {% for error in form.last_name.errors %}
        <p>{{ error }}</p>
        {% endfor %}
      </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="id_password1" class="form-label">Password</label>
      <input
        type="password"
        name="password1"
        class="form-control"
        id="id_password1"
        required
      />
      {% if form.password1.errors %}
      <div class="text-danger">
        {% for error in form.password1.errors %}
        <p>{{ error }}</p>
        {% endfor %}
      </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="id_password2" class="form-label">Confirm Password</label>
      <input
        type="password"
        name="password2"
        class="form-control"
        id="id_password2"
        required
      />
      {% if form.password2.errors %}
      <div class="text-danger">
        {% for error in form.password2.errors %}
        <p>{{ error }}</p>
        {% endfor %}
      </div>
      {% endif %}
    </div>

    <div class="d-flex justify-content-end">
      <button type="submit" class="btn btn-danger">Sign Up</button>
    </div>
  </form>

  <br />
  <div class="text-center">
    <p>
      Already have an account?
      <a href="{% url 'login' %}" class="text-body-secondary fw-bold">Login</a>
    </p>
  </div>
</div>

{% endblock %}